server:
  port: 8080

spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: NEVER
  quartz:
    job-store-type: jdbc
    jdbc:
      initialize-schema: ALWAYS
    properties:
      org.quartz.scheduler.instanceId: AUTO
      org.quartz.scheduler.instanceName: pinkdiary-batch
      org.quartz.jobStore.class: org.springframework.scheduling.quartz.LocalDataSourceJobStore
#      org.quartz.jobStore.driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
      org.quartz.jobStore.driverDelegateClass: dev.hoon.quartzmanager.quartz.CustomStdJDBCDelegate
      org.quartz.jobStore.isClustered: true
      org.quartz.jobStore.useProperties: true

application:
  core:
    datasource:
      url: jdbc:mysql://localhost:13306/core_db?characterEncoding=UTF-8&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: passwd
      driver-class-name: com.mysql.cj.jdbc.Driver


# for development
logging:
  level:
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE